using System.Globalization;
using Xunit;

namespace Euler
{
    /// <summary>
    /// Even Fibonacci numbers
    /// 
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    /// By starting with 1 and 2, the first 10 terms will be:
    ///
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    /// find the sum of the even-valued terms.
    /// 
    /// <seealso href="https://projecteuler.net/problem=2"/>
    /// </summary>
    public sealed class Problem002
    {
        private const string Answer = @"4613732";
        
        [Fact]
        public void Test()
        {
            var actual = GetAnswer();
            Assert.Equal(Answer, actual);
        }

        [Fact]
        public void WellKnownTest()
        {
            var expected = "10";
            var actual = GetAnswer(10);
            Assert.Equal(expected, actual);
        }

        public static string GetAnswer(long limit = 4000000L)
        {
            long result = 0;

            long prev = 1;
            long current = 2;

            // Iterate only every 3-th term of Fibonacci sequence
            while (current < limit)
            {
                result += current;

                var c = current;
                var p = prev;

                prev = 2 * c + p;
                current = 3 * c + 2 * p;
            }

            return result.ToString(CultureInfo.InvariantCulture);
        }
    }
}
